### ISSUE TITLE
Slow frame rates and bad organization of changelogs

### ISSUE THREAD

**Issue by Felipefpl** [nwn2fixes/player#1]
Hi, 1st of all i wanna say i can relate to what's being said here:

https://forum.bioware.com/topic/574648-terrible-frame-rate/

I have a computer that came years after both neverwinters were released yet frame rates on both are slow for no reason, is there a way to fix this just like it was done using dlls on fallout 2 here for example?

http://www.nma-fallout.com/forums/fallout-general-modding.18/

Regarding changelogs it's not pleasant to read them since all info is organized into phrases close to each other, it would be more pleasant to the eye/to read if they were organized like this text here. ;) Also, instead of one changelog's file per folder it would be better if it was one single file divided by sections: Original Campaign - Mask of the Betrayer, etc, etc, etc. If you want it to be pretty it could be even on .rtf format since Wordpad allows better format/looks.

That's all, thank you for all your work with this project and for your attention.

PS 1: there are several problems reported here https://forum.bioware.com/forum/152-technical-support/ and here https://forum.bioware.com/forum/165-general-discussion/ that deserve a look from you. ;)

PS 2: it is much better to use 7zip www.7-zip.org to compress the file just like community patch of NWN 1 uses it, i reduced the size of the package from 2.39 to 1.64 MB using the best settings i could.

**Comment by kevL** [comment]
hi Filip,

not much can be done on our end about framerates. NwN2 came out at at time when there was some cutting-edge graphics technology and they didn't quite get it right. I play on a c.2008 computer and am lucky to get 20fps with all shadows turned off (that's the major culprit), and use only drop shadows under characters. During fights my fps commonly drops to about 5.

check your user settings and drivers and whatnot.

oh, and if XOReos gets further off the ground, hardcoded things like the graphics engine will definitely be addressed there ...


I agree with you about the changelogs. But for the present, the structure and stuff is still a work-in-progress. Eventually i'd like to see one long list of changes, perhaps with only technotes relegated to subfolders. idk


.zip is the format used by GitHub. I'd prefer 7-zip too.

anyway, game on
