### ISSUE TITLE
SOZ : Being healed from a shrine of waukeen does not remove level drain effects

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#11]
I paid 500 gold to get healed at the shrine of waukeen at rassatan and it didnt remove the level drain effects from my party at all...

**Comment by kevL** [comment]
the clerics at the shrines won't remove bad effects. They simply heal.

bogus, but not a bug

**Comment by Question2** [comment]
But every "heal me" option in NWN 2 except for the shrines in waukeen remove all bad effects...

I mean, why else would you pay 500 gold? You can heal to full by paying 50g at an inn.

Players need an option in SOZ to remove bad effects if they dont have a cleric capable of casting restoration.

**Comment by kevL** [comment]
I agree. But it's still by design and not a technical bug.
