### ISSUE TITLE
2 MotB DLG fixes from JOG's Modding Corner

### ISSUE THREAD

**Issue by NinjaSpectre** [nwn2fixes/player#12]
MotB: Lurure Bears Bugfix
MotB: Ice-Troll-Lodge

Downloads from [JOG's Neverwinter Nights 2 Corner](http://mods.jo-ge.net/nwn2/index.htm)

I ran across these two DLG fixes and looked them over.  They have been changed how the author describes and address issues that haven't been patched.  I personally haven't tested them out in game; I don't have useful saves to do so near these areas (especially for the Wells of Lurure).  That being said, everything looks good as far as I can tell.

**Comment by kevL** [comment]
I took a look then slid them in as they are

https://github.com/nwn2fixes/player/commit/cbf4b170aa3e0d29bf700c977b8b1ad6ece23a17
