### ISSUE TITLE
DR belts appear to be bugged

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#15]
Not sure whats up with these, the DR belts that give DR to a certain damage type like the archer's belt are only worth 1 gold and the description seems bugged...see screenshot.

![nwn6](https://user-images.githubusercontent.com/1191378/45551488-78a9a880-b871-11e8-9e60-28e3ad741f52.jpg)

**Comment by Question2** [comment]
Uh, so do they actually provide any DR?

And would it be possible to edit the description to say what DR it protects against and what bypasses it, so players can actually know what it does? Like : DR 5 vs slashing, etc.

**Comment by Question2** [comment]
I mean, the actual text of the description, with the fluff bits? The part where it says stuff like "The contests to decide who...."

So for example, the archer's belt, does it provide DR 5 to piercing only?

**Comment by kevL** [comment]
unfortunately SetDescription() doesn't work properly ...

with the weird-looking stat description it should ... set something up in the toolset and test it – I did but that was a long time ago, i tried various things but eventually had to accept the borky description iirc
