### ISSUE TITLE
SOZ : Strange druid encounter, infinite exp glitch

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#16]
The strange druid encounter in Samarach can lead to an infinite xp glitch. If you use intimidate to force the druid to back off, and then choose to attack, the conversation ends, you get 100 xp for using intimidate, but the battle does not start and you can repeat it infinitely.

**Comment by Question2** [comment]
![nwn7](https://user-images.githubusercontent.com/1191378/45580409-1766f100-b8d4-11e8-8c69-fd0132afc645.jpg)

**Comment by kevL** [comment]
done

https://github.com/nwn2fixes/player/commit/53f6f03dc096bd8621101521fee9710e6b4bcd06
