### ISSUE TITLE
Shield AC from shield spell stacks with any actual shields you have equipped

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#17]
With a heavy shield equipped, you still get +4 AC from the shield spell because the heavy shield's AC is not considered a shield bonus. If you have a +1 heavy shield equipped, only the +1 part is considered a shield AC bonus.

So if you have 20 AC with a heavy shield equipped, you would get 24 AC after casting shield on yourself. If you have 21 AC with a +1 heavy shield equipped, you would get 24 AC and the warning message that the shield AC is not stacking.

**Comment by Question2** [comment]
As you said, nwn2 is 3.5e which doesnt allow stacking...(you cant stack enhancement bonuses for stats for example).

But its stacking which should be a bug...

**Comment by kevL** [comment]
20 nonmagical AC
+1 shield ac
+4 shield spell
= 24 means that shield enhancement didn't stack

**Comment by Question2** [comment]
A heavy shield gives 2 shield AC by default though.

**Comment by kevL** [comment]
the non-magical bits stack

**Comment by Question2** [comment]
Not by 3.5 rules at least : 

Armor/Shield Bonus

Each armor grants an armor bonus to AC, while shields grant a shield bonus to AC. The armor bonus from a suit of armor doesn’t stack with other effects or items that grant an armor bonus. **Similarly, the shield bonus from a shield doesn’t stack with other effects that grant a shield bonus.** 

http://www.d20srd.org/srd/equipment/armor.htm#armorShieldBonus

IIRC NWN2 handles armor/shield bonuses incorrectly. If you are wearing full plate (AC 8) and bracers of armor +4, you get a total of 12 AC which isnt correct by 3.5 rules.

**Comment by Question2** [comment]
Oh, didnt realise it was an engine issue. Looks like Xoreas is nowhere near complete either...

**Comment by kevL** [comment]
honestly, if i had better low-level programming skills i'd be working on it
