### ISSUE TITLE
SOZ : Yuan ti holy guardians are incorrectly immune to paralysis

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#21]
They should not be immune to paralysis, they should be immune to poison though. They cannot be paralyzed via the evard's tentacles spell.

Oddly enough, the named serpent guard in the ruined temple can be paralyzed by evard's tentacles.

![image](https://user-images.githubusercontent.com/1191378/45632190-12768d00-bae0-11e8-83d3-16ded56dec39.png)

**Comment by kevL** [comment]
That particular Yuan-ti is wearing ring a Ring of Freedom of Movement

**Comment by Question2** [comment]
Huh, thats pretty weird. Thanks for letting me know.

**Comment by kevL** [comment]
k
