### ISSUE TITLE
SOZ : Some enemies have incorrect alignments

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#22]
The following enemies should be evil but are not (they are not affected by the holy weapon property) : 

-The special quest only bandits that appear near new leaf after talking to the new leaf quartermaster

-Snaketongue assassins (human in robes) that appear on the overland map after you meet Jordan Wright at the Conyberry inn

**Comment by kevL** [comment]
I'll upload SnakeTongue Assassins as evil ... the NewLeaf shortage is more complicated: at a glance or two it uses either the Assassins or Bandits at different times. But i'm not comfortable making the Bandits evil so i guess they stay neutral - it would take an indepth study of the NewLeaf shortage quest to make an informed decision

**Comment by Question2** [comment]
Uh...arent bandits pretty much evil anyway? You have to be evil to rob people in the first place. These ones dont let you parley either, they immediately try to kill you because you were seen talking with the new leaf quartermaster.

The new leaf bandits are working for the snaketongue cult and are carrying snaketongue statues that lets you find their hideout.

**Comment by kevL** [comment]
I guess it comes down to a definition issue: i don't regard "bandits" as ipso facto evil. The average bandit in the medieval era, for example, was just trying to make a living without being some noble's serf. An alignment of ChaoticNeutral would work there. The transition into evil is, like a pleasure in others' pains. For most bandits, robbery was best when it was impersonal and expedient:

bandit: "Give me your loot."
victim: "Okay, here you go."
bandit: "Have a nice day!"

vs

snaketongue: "Give me your loot."
victim: "Okay, here you go."
snaketongue: "Now I'm going to rip your entrails out and eat them anyway."

**Comment by NinjaSpectre** [comment]
I agree that banditry is a point of view issue... just ask a chromatic dragon 😉

**Comment by Question2** [comment]
I seem to vaugely recall that D&D had a pretty black and white view of morality in that doing evil things for good ends is still considered evil. I cant really remember where that was discussed though...something to do with the book of vile darkness probably.

The forktongue bandits for new leaf were holding the town hostage...the quartermaster tells you that they threatened to kill everyone if they told others about the bandits.

If we want to get into grey areas, then the deluded cultists that TRULY believe they are saving the world by handing it over to the yuan ti arent evil...but im pretty sure that under D&D rules they would be considered evil.

**Comment by kevL** [comment]
there are people who want the entire alignment system to simply go away ...

**Comment by NinjaSpectre** [comment]
I always found it perplexing that a Paladin had to be Lawful Good even though their patron deity wasn't.
