### ISSUE TITLE
Bigby's forceful hand seems bugged

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#24]
I just tried casting it on a swamp cult cultist...instead of knocking him down however, the hand appeared, did one animation, then dissapeared. The cultist is now standing there doing nothing and has not moved for several rounds. He does not have the dazed status icon and is not knocked down.

I just checked my combat log and it doesnt mention anything to do with the cultist after i casted bigby's forceful hand, no bull rush check or anything.

I think a similar thing happened to me when i fought the banites, my character had no status icon indicating anything wrong with me, but i could not move. Clicking did nothing. If i tried to move with the WASD keys, i would get a message saying that i could not move due to a status effect, but no status effect icon was visible.

I think the script is manually applying the dazed effect but its missing the status icon and isnt generating any rolls in the combat log so players have no idea what is going on. And the knockdown effect appears to be missing.

**Comment by Question2** [comment]
Bigby's clenched fist doesnt appear to work either...casted it on Es'San, he failed the SR and fort save....but didnt get stunned.

![image](https://user-images.githubusercontent.com/1191378/45694779-5aaab380-bba3-11e8-8abd-b7fb5e4fb6b4.png)

In later rounds, I noticed that he was still failing saves against the DC 35 fist but could keep casting spells for some reason...

![image](https://user-images.githubusercontent.com/1191378/45694923-a65d5d00-bba3-11e8-8d55-1cab8df7b1fa.png)

**Comment by Question2** [comment]
Just realised that the weird spell issues im seeing may be due to reeron's spell fixes pack being merged with kaedrin's pack. Going to do some more testing after cleaning out the script folder.

**Comment by kevL** [comment]
okay
