### ISSUE TITLE
Party AI

### ISSUE THREAD

**Issue by fleenots** [nwn2fixes/player#33]
I am having serious issues with the Party AI. Turning it on/of in the UI or in the Character windows, many times don't affect anything. Here is a save with an example
https://1drv.ms/u/s!AthEKc_8zvExiAC6xz41ohjYScXz

**Comment by fleenots** [comment]
I can still give following and attack orders through the quick chat

**Comment by kevL** [comment]
try this

https://drive.google.com/file/d/1tco-HeUDddXgapD1D5WjqBuO8Ll4xtMC/view?usp=sharing

(will be deleted after a few days/ a few weeks)

I went through and organized your characters and went through and clicked on every setting in each of their Behaviors tabs -- sometimes state gets mixed up on what's actually been set on those tabs. They seem to work okay on my machine (only Nwn2Fixes in override)

**Comment by fleenots** [comment]
Great!!!
Thanks
