### ISSUE TITLE
Bug in motb dialogue allows infinite Safiya influence

### ISSUE THREAD

**Issue by rsw0x** [nwn2fixes/player#35]
When speaking to Fentomy at Lakeshore the lore check is capable of being used multiple times, each time granting +11 influence with Safiya. 

Pick lore check -> "Why are you really here?" -> can pick lore check again.

Upon inspecting the dialogue file there are other skill checks with similar results so likely not restricted to the lore option.

**Comment by kevL** [comment]
https://github.com/nwn2fixes/player/commit/ca193f835e1f020601cc7809df097d4c2f41c682

thank you sir,
