### ISSUE TITLE
OC Khelgar monk or fighter choice

### ISSUE THREAD

**Issue by FerionVirian** [nwn2fixes/player#39]
https://gamefaqs.gamespot.com/boards/922154-neverwinter-nights-2/74215962
_When you complete three trials and speak with Hlam there is an option to say

"You've learned what you need to learn - you don't need to follow them to be a strong fighter."

Influence check for this dialogue option is bugged, it's supposed to success when you have more then 10 points of influence with Khelgar, but it actually works only when you have EXACTLY 10 point of influence._

is it possible to change influence check from ==10 to >=10 or already fixed?

**Comment by kevL** [comment]
looks like those checks have all been changed to ">9"

10_hlam.DLG
3063_hlam.DLG
