### ISSUE TITLE
OC Alteration powder

### ISSUE THREAD

**Issue by FerionVirian** [nwn2fixes/player#42]
Bluff dryad into giving me alteration powder: quest closed, quest log say - dryad gave me powder. but no powder in inventory. even Sand in dialog said i must keep powder until trial.
https://drive.google.com/file/d/1LUQZBMk3QQahwmEv9QFZtQBoKZMz-G4p/view?usp=sharing
nearest save file - travel to duskwood speak with dryad.

**Comment by kevL** [comment]
https://github.com/nwn2fixes/player/commit/424469a6348f1aa4fa65a0952e7ea9d3af019077

thanks for the save file. I'm not certain that the PC might not end up with 2 Alteration Powders as a result of this change (but that can be dealt with later if so).
