### ISSUE TITLE
OC Ryte of Tyr

### ISSUE THREAD

**Issue by FerionVirian** [nwn2fixes/player#44]
after Khelgar kill Lorne - PC teleported to CK basement.
save before fight
https://drive.google.com/file/d/1Ih9H-ROB2nIWC3jVXQxz25UZaM-Inkj1/view?usp=sharing
https://drive.google.com/file/d/1MvRzUSKxq49yQ5wHPbG8ng1k4GhuDHe0/view?usp=sharing
save at basement
https://drive.google.com/file/d/16UepayK8KbNWE_3K9QPpG-7jqH36Y1HD/view?usp=sharing

**Comment by kevL** [comment]
https://github.com/nwn2fixes/player/commit/95c0187191023ac06192ea56c70b68ca27c7210f

i think i got it

thanks for the saves again, they're critical for stuff like this
