### ISSUE TITLE
Auto-Detect Doesnt Work Properly

### ISSUE THREAD

**Issue by Felipefpl** [nwn2fixes/player#47]
Version 1.23 - Win7 x64 - Intel HD 2000

Auto-detect only works to enable shadows at MAX, it doesnt change the resolution or any other options.

**Comment by kevL** [comment]
is that an integrated video chip on your motherboard?


(recommended to use a read, 3rd party vidcard)

**Comment by Felipefpl** [comment]
yeh, it's a integrated video card, unfortunately i cant have a good video card since i'm poor and cant buy a new one. :/

I'm asking about the auto-detect option because this settings works PERFECTLY on the witcher, choosing the best options to run the game full speed. This doesnt happen with the setting in nwn 2. :/

**Comment by kevL** [comment]
heya, i won't apologize for NwN2 ... it is what it is eh

**Comment by Felipefpl** [comment]
Ok, no pressure into this, just reported because this surely is a bug, i wonder how the obsidian devs didnt see this.

**Comment by kevL** [comment]
they were rushed. The parent company declared bankruptcy shortly after nwn2 was released ...

or something like that -- I've plodded through a lot of the nwn2 stuff and it shows signs of being very very rushed.

**Comment by Felipefpl** [comment]
I understand, that surely explains the problem. Thanks for the info.

**Comment by kevL** [comment]
kk
