### ISSUE TITLE
Graphics/Fonts Are Slightly Out of Focus

### ISSUE THREAD

**Issue by Felipefpl** [nwn2fixes/player#48]
It doesnt matter if i choose 800x600 or 1600x900 (max my 20' monitor supports), both are ugly (being less ugly on upper resolutions but even so the font is small, still out of focus and hard to read)

**Comment by kevL** [comment]
not sure what can be done about that

**Comment by Felipefpl** [comment]
Would be not possible to at least replace the fonts used by the game with HD fonts that look good in any resolution?

**Comment by kevL** [comment]
i think you can -- look into fontfamily.xml and search for the .ttf files that Nwn2 uses ...

but changing font-size can seriously bork the UI. If a string doesn't fit inside a/the specified rectangle it doesn't show up at all.
