### ISSUE TITLE
Turning the screen is too fast

### ISSUE THREAD

**Issue by Felipefpl** [nwn2fixes/player#49]
Even setting the option at minimum the turning/scrolling/whatever of the screen is too fast, not a problem for some ppl i believe but awful for those with motion sickness like me.

**Comment by kevL** [comment]
hey Felipe

although as you say it's a preference (not a fix per se) here are my settings for cameramodes -- in

docs/Neverwinter Nights2/nwn2player.ini

`
[Exploration Mode Options]
;wheelzoom
Mousewheel_Speed_Min=5.000000
Mousewheel_Speed_Max=20.000000
Mousewheel_Speed_Default=10.000000
Mousewheel_Speed_Current=9.950001
;mouselook
Mouse_Turn_Min=0.100000
Mouse_Turn_Max=2.000000
Mouse_Turn_Default=1.000000
Mouse_Turn_Current=0.955000
;edgeturn - this is not in Options
Edge_Turn_Min=1.000000
Edge_Turn_Max=5.000000
Edge_Turn_Default=2.500000
Edge_Turn_Current=2.820000
;edgescroll
Edge_Move_Min=0.100000
Edge_Move_Max=1.000000
Edge_Move_Default=0.500000
Edge_Move_Current=0.325000
;keyscroll also keyturn and keyzoom-in/out
Keyboard_Move_Min=1.000000
Keyboard_Move_Max=5.000000
Keyboard_Move_Default=2.500000
Keyboard_Move_Current=3.720000
Fade Objects=1
Show Move Cursor=1
Mouseover Highlight Flags=74
CameraMode=1
LeftClickAction=1
Ceiling Draw Mode=0
PossessAsDefault=1
CameraFollowAlways=0
MouseMovement=1
Enable ScreenEdgeCameraTurn=1
Enable ScreenEdgeCameraMove=0

[Strategy Mode Options]
;wheelzoom
Mousewheel_Speed_Min=1.000000
Mousewheel_Speed_Max=10.000000
Mousewheel_Speed_Default=5.000000
Mousewheel_Speed_Current=3.970000
;mouselook
Mouse_Turn_Min=0.100000
Mouse_Turn_Max=2.000000
Mouse_Turn_Default=1.000000
Mouse_Turn_Current=0.955000
;edgeturn
Edge_Turn_Min=1.000000
Edge_Turn_Max=10.000000
Edge_Turn_Default=2.500000
Edge_Turn_Current=5.050000
;edgescroll
Edge_Move_Min=0.100000
Edge_Move_Max=2.000000
Edge_Move_Default=1.000000
Edge_Move_Current=0.955000
;keyscroll
Keyboard_Move_Min=1.000000
Keyboard_Move_Max=5.000000
Keyboard_Move_Default=2.500000
Keyboard_Move_Current=2.480000
Fade Objects=1
Show Move Cursor=1
Mouseover Highlight Flags=74
CameraMode=3
LeftClickAction=2
Ceiling Draw Mode=2
PossessAsDefault=1
CameraFollowAlways=0
MouseMovement=1
Enable ScreenEdgeCameraTurn=0
AutoCenterFreeCam=0
SelectedCharacterCursor=1
Enable ScreenEdgeCameraMove=1

[Character Mode Options]
;wheelzoom
Mousewheel_Speed_Min=1.000000
Mousewheel_Speed_Max=10.000000
Mousewheel_Speed_Default=5.000000
Mousewheel_Speed_Current=3.970000
;mouselook
Mouse_Turn_Min=0.100000
Mouse_Turn_Max=2.000000
Mouse_Turn_Default=1.000000
Mouse_Turn_Current=0.955000
;edgeturn
Edge_Turn_Min=1.000000
Edge_Turn_Max=10.000000
Edge_Turn_Default=5.000000
Edge_Turn_Current=2.980000
;followdelay
Camera_Lag_Min=0.100000
Camera_Lag_Max=2.500000
Camera_Lag_Default=1.000000
Camera_Lag_Current=0.484000
Fade Objects=1
Show Move Cursor=1
Mouseover Highlight Flags=74
CameraMode=0
LeftClickAction=1
Ceiling Draw Mode=1
PossessAsDefault=1
CameraFollowAlways=0
MouseMovement=1
Enable ScreenEdgeCameraTurn=1
`

back up your .ini first (in /MyDocuments) then paste that in and try it. I'm not sure how adept you are at this stuff, so take it easy ... but i agree that the stock camera settings are gimped; the above settings should slow it down a lot,

and note that some of the important camera settings are not even shown in Options -- so you gotta do it yerself

ps. If you'd rather not overwrite your camera settings with mine in toto, look for the Min/Max/Default/Current groups above, and try just those.

**Comment by Felipefpl** [comment]
kevL - thank you very much for your config, i used the exploration ones and it worked, amazing that those values you added in the .ini file the are smaller than the ones i got decreasing the bars of those configurations to the minimum made those very same bars to be in different positions like if i had increased the speed of scrolling, surely a bad bug.

**Comment by kevL** [comment]
it's not really a bug ...
the Min value is going to be the leftmost setting of the slider in Options,
the Max value is the rightmost setting of the slider

the Default value is where the engine initializes the slider if nwn2player.ini hasn't been created yet

and the Current value is your current setting to play the game with.


the egregious oversight (aka bug) is not showing the Exploration:edgeturn slider in the Options panel. I mean, moving the mouse to the edge of the screen to swivel the camera around is the most important setting of all ...
