### ISSUE TITLE
Bugged elven chanmail in the OC

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#5]
The elven chainmail that can be obtained from the collector's mansion is listed as mithral, but max dex bonus and arcane spell failure are iron stats. Another set of elven chainmail can be obtained in the arvahn ruins and those have the correct stats.

**Comment by kevL** [comment]
Elven Ceremonial Armor is listed as iron in its resref (silly yeh, but changing it to mithral is too close to a customization imo)

**Comment by Question2** [comment]
But the description lists it as mithral, and theres another set of elven chainmail in the game that does have the mithral stats...

**Comment by kevL** [comment]
if you can tell me exactly where the elven chainmail is in the Collector's Mansion i'll have another look for it, since all I could find was the Elven Ceremonial Armor (fullplate) in the vault on the upper floor. Even just the accurate name of it that appears in your inventory could be helpful ...

**Comment by NinjaSpectre** [comment]
I looked into this a bit and posted my findings below.  TLDR everything looks fine the way it is.

Collector's Mansion - Blacklake - Start of Chapter Two
Elven Ceremonial Armor
Full Plate (AC 8, Max Dex AC Bonus 1, Penalty 6, Spell Failure 35%)
Enchantments (AC Armor+1, Spell Focus: Conjuration, Enchantment, Divination, Evocation)

Bounty Hunters - Forest - Random after Trial
Elven Chainmail
Chainmail (AC 5, Max Dex AC Bonus 2, Penalty 5, Spell Failure 30%)
Enchantments (AC Armor+3, Hide+6, Move Silently+6, Weight-60%)

Riverguard Keep - Ruins of Arvahn - Before finding Haven
Mithral Elven Chainmail
Mithral Chainmail (AC 5, Max Dex AC Bonus 4, Penalty 2, Spell Failure 20%)
Enchantments (AC Armor+3, Universal+1)

**Comment by kevL** [comment]
poking through blueprints in the toolset, the only "elven" or "chainmail" item I've seen that is listed as Mithral but doesn't use a mithral entry from ArmorRuleStats.2da (eg, "Mithral Chainmail" in its Armor type field) is

**Aslyferund Elven Chain** (material says "Metal (Mithral)" but Armor type says standard "Chain Shirt")

@NinjaSpectre do you know where can i find the blueprint for that Bounty Hunters "Elven Chainmail" ... I'd like to have a look at it. Is the .UTI in one of the OC modules, the OC Campaign folder, etc? I just can't find it yet

**Comment by NinjaSpectre** [comment]
Don't know if this will be helpful, but here goes.
Module: 2200_Port_Llast, Area: generic forest, Creatures: _Rivals -> Niyra ->Inventory

**Comment by kevL** [comment]
found it, thanks. Yep that one's borked too

am kinda busy atm though ...

**Comment by kevL** [comment]
https://github.com/nwn2fixes/player/commit/89d091441c006d3aec754e1824f09bd092284db3
https://github.com/nwn2fixes/player/commit/9a6d5d66b813c005a43d7432810aaf1995de8972
https://github.com/nwn2fixes/player/commit/c4a31db713df4f0846279e06733021e0c6500ca5

**Comment by Question2** [comment]
My bad, remembered wrongly, was probably the bounty hunters elven chainmail.
