### ISSUE TITLE
MOTB Shamans boon

### ISSUE THREAD

**Issue by FerionVirian** [nwn2fixes/player#50]
Can you look into quest Shamans boon in MOTB.
Ingame chat states what Okku gain new lvl. But Okku didn't acquire new lvl.

**Comment by kevL** [comment]
try this

https://github.com/nwn2fixes/player/commit/6456368ebbead8b0832d5cc76eac8767d394b28a

untested so am not sure what repercussions it has ...

**Comment by FerionVirian** [comment]
my nearest save in death god vault.
https://drive.google.com/file/d/1ztlq3rneM6XNmPUpaZ7pY6TtF5wLC71f/view?usp=sharing

**Comment by kevL** [comment]
thanks, got 'em

there's an issue with Okku's equipment remaining in his inventory ... looking at it ...

**Comment by kevL** [comment]
Having look a bit more, it looks to me like Okku is supposed to get a bite/claw upgrade but not advance a level. However since the dialog says he advances a level he's gonna advance a level AND get the bite/claw upgrade

that's quite a big boost in Okku's power ...

**Comment by kevL** [comment]
https://github.com/nwn2fixes/player/commit/735ffda2c1900699995d39633199b101fab94b50
