### ISSUE TITLE
About Nwn 2 client extension

### ISSUE THREAD

**Issue by Felipefpl** [nwn2fixes/player#51]
I saw that the client contain several fixes that fix crashes/stuttering of the game, i was wondering if it was possible to merge all fixes with nwn2fixes because... why not? Better download a single package instead of one and they are fixes anyway, right?

**Comment by kevL** [comment]
hey Felipe,
if you (or someone) wants to create an all-in-one package i can't stop ya.

But from my perspective, the CE is a very different beast. As you may know it's a custom-coded frontend loader for the executable itself (by Skywing who has a LOT of knowledge about the game engine) ; nwn2Fixes is merely ingame fixes that can be done in the toolset.

at best all I'd do is put a suggestion in the Fixes doc and link to Skywing's CE

**Comment by kevL** [comment]
I added a note on the frontpage
https://github.com/nwn2fixes/player
https://github.com/nwn2fixes/player/commit/49ba19905aee360a791a4fe4c1cd0268a1c6f2ae

**Comment by Felipefpl** [comment]
Ok, thanks for the info about this.
