### ISSUE TITLE
Jun14 version nukes Kaedrin PRC compatibility

### ISSUE THREAD

**Issue by Daisho11** [nwn2fixes/player#55]
Just installed the newest nwn2fixes and Kaedrin's PRC mod no longer works in game.

**Comment by kevL** [comment]
can you be more specific?
And have you run a duplicate file checker against your /Override and resolved conflicts?

if i have to, today's commit can be reverted but id like to know why

**Comment by kevL** [comment]
before you installed jun14, were you using the previous Nwn2Fixes and things worked?

ie Did the jun14 update break the kPrC pack?

**Comment by kevL** [comment]
here's the list of changes
https://github.com/nwn2fixes/player/commit/a41025672b1b184c4c027a0769a74bca578a4b57

just a bunch of recompiled scripts. But unfortunately i don't see anything that could interefere with Feats @ levelup.

i suspect it's a 2da issue ...

**Comment by Daisho11** [comment]
It did work with the previous version of nwn2fixes, though I was having an issue with telthor companion for spirit shaman being stuck at level 1, so I decided to do some testing and digging around. I have since uninstalled the game, completely removed all leftover files, then reinstalled with only kaedrin's prc, tony k ai, some appearance stuff, and the issue still persisted. Also, I noticed that it was only the kaedrin prc feats that were not showing up. The spells and classes were still there.

**Comment by Daisho11** [comment]
I have found a workaround that seems to make everything work so far. In my override folder, I added a "z" to the beginning of the kaedrin prc folder name, to see if folder order would do anything, and it seems (so far) to have fixed the issue. Hopefully they may give some clues as to what might be causing this issue.

**Comment by kevL** [comment]
| It did work with the previous version of nwn2fixes

( atm i'm thinking you could have resolved some issues with the previous version against other things in your /override, maybe forgot about it, then just slapped in the new version of Fixes, and the probls reappeared / just a guess though )

| I was having an issue with telthor companion for spirit shaman being stuck at level 1

some time ago I did have to fix animal companions stuck at L1, i think for compatibility with the kPrC pack. i might have missed a possible quirk w/ the telthor companion ...

| I noticed that it was only the kaedrin prc feats that were not showing up.

hm. Duplicate Feat.2da ... ( Nwn2Fixes and the kPrC both distribute Feat.2da - the one in Fixes is not too important iirc : go with Kaedrin's )

| In my override folder, I added a "z" to the beginning of the kaedrin prc folder name, to see if folder order would do anything, and it seems (so far) to have fixed the issue.

that is strongly indicative that you've got duplicate files in your /override. Perhaps get a better duplicate file checking app than the one in CCleaner

**Comment by Daisho11** [comment]
I used auslogics duplicate file finder and it turned up some duplicates. I removed all the duplicates with it, but the problem still persists (unless I change the folder order in override).  Is there a duplicate file finder that you recommend instead?

**Comment by kevL** [comment]
i use [AllDup](http://www.alldup.de/alldup_help/alldup.php)
It takes a while to figure out and set up, but it's powerful/adaptable.

( Remember that resources in Modules' .hak files override the /override )

And a note about the "z" folder prefix -- i haven't tried to figure out exactly why that appears to work for some people, but having done some coding in c++/c# it might not be because "z" is the last letter of the english alphabet ; it could rather be that that folder was the last folder created or relabeled ... / just sayin' that that tactic might not always work as expected


ps. correction re. AnimalCompanions -- that was for MetaPrepa not nwn2fixes.


So have you got things working to satisfaction atm?

**Comment by kevL** [comment]
here's a question: is the issue specific to a Campaign/module or does it happen no matter what Campaign/module is loaded ?
