### ISSUE TITLE
Corrupted download

### ISSUE THREAD

**Issue by Felipefpl** [nwn2fixes/player#57]
@kevL - i downloaded the file with the fixes but both 7zip/winrar reported that there is a corruption on it.

Side note: i saw these on nexus mods and i thought they could be good fixes to be added here:

https://www.nexusmods.com/neverwinter2/mods/907

https://www.nexusmods.com/neverwinter2/mods/1170

https://www.nexusmods.com/neverwinter2/mods/1185

**Comment by kevL** [comment]
hey Felipe,
i just downloaded the "player-master.zip" under the Code button on page:
https://github.com/nwn2fixes/player

and 7-zip opens it okay.

(will take a look at those mods as time permits)

**Comment by Felipefpl** [comment]
That's the place where i downloaded from, i downloaded again and it was corrupted, then i downloaded another time and it was Ok, weird stuff....

Good to know you'll look at those fixes. :+1:
