### ISSUE TITLE
Bugged exit to waypoint in the mere of dead men (act 2, OC)

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#6]
After entering the mere via the destroyed west harbor version, the exit says "world map" but clicking on it does nothing and you cannot access the world map. Either you should be allowed to access it, or the exit should lead back to the destroyed west harbor.

**Comment by kevL** [comment]
The note in the script for that worldmap says "Should only be enabled after the module completes."

ie, no return till the job gets done

**Comment by Question2** [comment]
Yes but i can see the exit, just that clicking on the blue circle does nothing.

**Comment by kevL** [comment]
yes, I wouldn't have designed it that way i suppose. I would probably send the player a message to the effect that the worldmap is disabled until ... further notice. But at least the player knows that that's where the exit is/ will be ...

it's not a bug, it's simply bad design.
