### ISSUE TITLE
SOZ : Wraiths in crypt NE of Nimbre cannot be hurt by +1 arrows

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#9]
Using a longbow with +1 arrows, i cannot hurt the wraiths in the crypt at all. I can see them hit with the graphical effect, but they cause no damage nor is there any message in the combat log about damage reduction. There is also no message about missing due to concealment.

Maybe the check for magical weapons is being made against the bow rather than the arrow?

**Comment by kevL** [comment]
sounds like an engine issue - am not comfortable dealing with that (combat mechanics are VERY hardcoded, unfortunately)

Am looking into Mephasm and Redfeyer,
